import Register from "@/components/login/Register";
import Thanks from "@/components/login/Thanks";
import useScreenHeight from "@/hooks/useScreenHeight";
import { Grid } from "@nextui-org/react";
import { getCookie } from "cookies-next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from "./Register.module.css";

export default function Signup() {
	const router = useRouter();
	const user = getCookie("user");
	const screenHeight = useScreenHeight();
	const [signedUp, setSignedUp] = useState<boolean>(false);

	useEffect(() => {
		if (user && router.pathname !== "/chat") {
			router.push("/chat");
		}
	}, [user]);
	return (
		<>
			<Head>
				<title>Sign up</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{!user && (
				<Grid className={styles.register} css={{ background: "$primaryBg", height: screenHeight }}>
					{!signedUp && <Register setSignedUp={setSignedUp} />}
					{signedUp && <Thanks />}
				</Grid>
			)}
		</>
	);
}
